### ISSUE TITLE
Getting started - Adding and commiting - Add link / text edit

### ISSUE THREAD

**Issue by ElizabethFernandes** [JeremyBuhler/rc-git#2]
At: https://ubc-library-rc.github.io/intro-git/content/02_getting_started.html

I highlighted what seems to be a note to yourself.

"Adding and committing
We will now create and save our first project file. (...)

INPUT
$ touch index.md
The .md extension is for text files written using Markdown, a lightweight markup language with plain text formatting syntax. For more on Markdown see **(link to Markdown resource, add .md cheatsheet to resources list)** "

I'd assume the referred link is: https://guides.github.com/features/mastering-markdown/
.md cheatsheet available at: https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet however, last updated in 2017.

**Comment by JeremyBuhler** [comment]
Hi Elizabeth, thanks for catching this and for suggesting possible resources! I updated the pages with the links you provided.
