### ISSUE TITLE
Master vs. Main Terminology in Intro to Git Workshop

### ISSUE THREAD

**Issue by Francoisdt14** [JeremyBuhler/rc-git#3]
Hi,

I noticed on this [page](https://ubc-library-rc.github.io/intro-git/content/03_sync.html) the term 'master' is used (step 2 - ‘git push -u origin master’). When chatting to Evan Thornberry he brought up the fact that 'main' is the new terminology. Should this be changed to main? 

Regards,

Francois

**Comment by JeremyBuhler** [comment]
Hi Francois, thanks for pointing this out! I changed 'master' to 'main' on the three pages where it occurred.

Cheers,
Jeremy
